feat: add support for redis serverless
cloudposse/terraform-aws-elasticache-redis pull request #235
Opened 2024-06-10 06:24 UTC by syphernl

## what

- Add support for Serverless Redis instances

## why

- Supporting Redis Serverless for demanding applications

## notes

- This upgrades the required version of the AWS provider from   ">= [5.27.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5270-november-27-2023)" to  ">=  [5.32](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5320-january-11-2024)" as this is the first release where `aws_elasticache_serverless_cache` was introduced

2024-06-10 16:34 UTC, Benbentwo approved these changes

2024-06-10 17:14 UTC, Benbentwo requested changes

2024-06-10 17:14 UTC, Benbentwo commented on main.tf
> +  endpoint_serverless = try(aws_elasticache_serverless_cache.default[0].endpoint.0.address, null)
```suggestion
  endpoint_serverless = try(aws_elasticache_serverless_cache.default[0].endpoint[0].address, null)
```

2024-06-10 17:14 UTC, Benbentwo commented on main.tf
> +  reader_endpoint_serverless = try(aws_elasticache_serverless_cache.default[0].reader_endpoint.0.address, null)
```suggestion
  reader_endpoint_serverless = try(aws_elasticache_serverless_cache.default[0].reader_endpoint[0].address, null)
```

2024-06-11 18:53 UTC, Benbentwo approved these changes

2024-06-11 18:53 UTC, Benbentwo commented
/terratest

2024-06-11 19:29 UTC, merged

2024-10-21 15:38 UTC, adamantike commented on variables.tf
> +# Add boolean to create a serverless cluster
This looks like a leftover comment, used for an AI to generate this variable code :)