add ability to restore cluster from snapshots #96
cloudposse/terraform-aws-elasticache-redis pull request #97
Opened 2020-12-15 17:45 UTC by skang0601

## what
Allows the ability to create redis cluster from snapshots

## references
* closes #96

2021-01-18 02:53 UTC, kurtmc approved these changes
This looks good to me. Is there anything stopping this from being merged?

2021-01-25 21:38 UTC, skang0601 commented
@kurtmc Merge conflict has been addressed. I don't think I have permissions to merge to this repo, do these changes look good for y'all?

2021-01-26 08:58 UTC, SweetOps requested changes

2021-01-26 08:58 UTC, SweetOps commented on variables.tf
> +  description = "(Optional) A single-element string list containing an Amazon Resource Name (ARN) of a Redis RDB snapshot file stored in Amazon S3. Example: arn:aws:s3:::my_bucket/snapshot1.rdb"
```suggestion
  description = "A single-element string list containing an Amazon Resource Name (ARN) of a Redis RDB snapshot file stored in Amazon S3. Example: arn:aws:s3:::my_bucket/snapshot1.rdb"
```

for consistency with other variables

2021-01-26 15:56 UTC, SweetOps commented
/test all

2021-01-27 11:56 UTC, SweetOps approved these changes

2021-01-27 11:57 UTC, merged